require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ChangeInsuredRateFromCarryingBillsController do

  def mock_change_insured_rate_from_carrying_bill(stubs={})
    @mock_change_insured_rate_from_carrying_bill ||= mock_model(ChangeInsuredRateFromCarryingBill, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all change_insured_rate_from_carrying_bills as @change_insured_rate_from_carrying_bills" do
      ChangeInsuredRateFromCarryingBill.stub(:all) { [mock_change_insured_rate_from_carrying_bill] }
      get :index
      assigns(:change_insured_rate_from_carrying_bills).should eq([mock_change_insured_rate_from_carrying_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested change_insured_rate_from_carrying_bill as @change_insured_rate_from_carrying_bill" do
      ChangeInsuredRateFromCarryingBill.stub(:find).with("37") { mock_change_insured_rate_from_carrying_bill }
      get :show, :id => "37"
      assigns(:change_insured_rate_from_carrying_bill).should be(mock_change_insured_rate_from_carrying_bill)
    end
  end

  describe "GET new" do
    it "assigns a new change_insured_rate_from_carrying_bill as @change_insured_rate_from_carrying_bill" do
      ChangeInsuredRateFromCarryingBill.stub(:new) { mock_change_insured_rate_from_carrying_bill }
      get :new
      assigns(:change_insured_rate_from_carrying_bill).should be(mock_change_insured_rate_from_carrying_bill)
    end
  end

  describe "GET edit" do
    it "assigns the requested change_insured_rate_from_carrying_bill as @change_insured_rate_from_carrying_bill" do
      ChangeInsuredRateFromCarryingBill.stub(:find).with("37") { mock_change_insured_rate_from_carrying_bill }
      get :edit, :id => "37"
      assigns(:change_insured_rate_from_carrying_bill).should be(mock_change_insured_rate_from_carrying_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created change_insured_rate_from_carrying_bill as @change_insured_rate_from_carrying_bill" do
        ChangeInsuredRateFromCarryingBill.stub(:new).with({'these' => 'params'}) { mock_change_insured_rate_from_carrying_bill(:save => true) }
        post :create, :change_insured_rate_from_carrying_bill => {'these' => 'params'}
        assigns(:change_insured_rate_from_carrying_bill).should be(mock_change_insured_rate_from_carrying_bill)
      end

      it "redirects to the created change_insured_rate_from_carrying_bill" do
        ChangeInsuredRateFromCarryingBill.stub(:new) { mock_change_insured_rate_from_carrying_bill(:save => true) }
        post :create, :change_insured_rate_from_carrying_bill => {}
        response.should redirect_to(change_insured_rate_from_carrying_bill_url(mock_change_insured_rate_from_carrying_bill))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved change_insured_rate_from_carrying_bill as @change_insured_rate_from_carrying_bill" do
        ChangeInsuredRateFromCarryingBill.stub(:new).with({'these' => 'params'}) { mock_change_insured_rate_from_carrying_bill(:save => false) }
        post :create, :change_insured_rate_from_carrying_bill => {'these' => 'params'}
        assigns(:change_insured_rate_from_carrying_bill).should be(mock_change_insured_rate_from_carrying_bill)
      end

      it "re-renders the 'new' template" do
        ChangeInsuredRateFromCarryingBill.stub(:new) { mock_change_insured_rate_from_carrying_bill(:save => false) }
        post :create, :change_insured_rate_from_carrying_bill => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested change_insured_rate_from_carrying_bill" do
        ChangeInsuredRateFromCarryingBill.stub(:find).with("37") { mock_change_insured_rate_from_carrying_bill }
        mock_change_insured_rate_from_carrying_bill.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :change_insured_rate_from_carrying_bill => {'these' => 'params'}
      end

      it "assigns the requested change_insured_rate_from_carrying_bill as @change_insured_rate_from_carrying_bill" do
        ChangeInsuredRateFromCarryingBill.stub(:find) { mock_change_insured_rate_from_carrying_bill(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:change_insured_rate_from_carrying_bill).should be(mock_change_insured_rate_from_carrying_bill)
      end

      it "redirects to the change_insured_rate_from_carrying_bill" do
        ChangeInsuredRateFromCarryingBill.stub(:find) { mock_change_insured_rate_from_carrying_bill(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(change_insured_rate_from_carrying_bill_url(mock_change_insured_rate_from_carrying_bill))
      end
    end

    describe "with invalid params" do
      it "assigns the change_insured_rate_from_carrying_bill as @change_insured_rate_from_carrying_bill" do
        ChangeInsuredRateFromCarryingBill.stub(:find) { mock_change_insured_rate_from_carrying_bill(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:change_insured_rate_from_carrying_bill).should be(mock_change_insured_rate_from_carrying_bill)
      end

      it "re-renders the 'edit' template" do
        ChangeInsuredRateFromCarryingBill.stub(:find) { mock_change_insured_rate_from_carrying_bill(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested change_insured_rate_from_carrying_bill" do
      ChangeInsuredRateFromCarryingBill.stub(:find).with("37") { mock_change_insured_rate_from_carrying_bill }
      mock_change_insured_rate_from_carrying_bill.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the change_insured_rate_from_carrying_bills list" do
      ChangeInsuredRateFromCarryingBill.stub(:find) { mock_change_insured_rate_from_carrying_bill }
      delete :destroy, :id => "1"
      response.should redirect_to(change_insured_rate_from_carrying_bills_url)
    end
  end

end
