require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ConfigCashesController do

  def mock_config_cash(stubs={})
    @mock_config_cash ||= mock_model(ConfigCash, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all config_cashes as @config_cashes" do
      ConfigCash.stub(:all) { [mock_config_cash] }
      get :index
      assigns(:config_cashes).should eq([mock_config_cash])
    end
  end

  describe "GET show" do
    it "assigns the requested config_cash as @config_cash" do
      ConfigCash.stub(:find).with("37") { mock_config_cash }
      get :show, :id => "37"
      assigns(:config_cash).should be(mock_config_cash)
    end
  end

  describe "GET new" do
    it "assigns a new config_cash as @config_cash" do
      ConfigCash.stub(:new) { mock_config_cash }
      get :new
      assigns(:config_cash).should be(mock_config_cash)
    end
  end

  describe "GET edit" do
    it "assigns the requested config_cash as @config_cash" do
      ConfigCash.stub(:find).with("37") { mock_config_cash }
      get :edit, :id => "37"
      assigns(:config_cash).should be(mock_config_cash)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created config_cash as @config_cash" do
        ConfigCash.stub(:new).with({'these' => 'params'}) { mock_config_cash(:save => true) }
        post :create, :config_cash => {'these' => 'params'}
        assigns(:config_cash).should be(mock_config_cash)
      end

      it "redirects to the created config_cash" do
        ConfigCash.stub(:new) { mock_config_cash(:save => true) }
        post :create, :config_cash => {}
        response.should redirect_to(config_cash_url(mock_config_cash))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved config_cash as @config_cash" do
        ConfigCash.stub(:new).with({'these' => 'params'}) { mock_config_cash(:save => false) }
        post :create, :config_cash => {'these' => 'params'}
        assigns(:config_cash).should be(mock_config_cash)
      end

      it "re-renders the 'new' template" do
        ConfigCash.stub(:new) { mock_config_cash(:save => false) }
        post :create, :config_cash => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested config_cash" do
        ConfigCash.stub(:find).with("37") { mock_config_cash }
        mock_config_cash.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :config_cash => {'these' => 'params'}
      end

      it "assigns the requested config_cash as @config_cash" do
        ConfigCash.stub(:find) { mock_config_cash(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:config_cash).should be(mock_config_cash)
      end

      it "redirects to the config_cash" do
        ConfigCash.stub(:find) { mock_config_cash(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(config_cash_url(mock_config_cash))
      end
    end

    describe "with invalid params" do
      it "assigns the config_cash as @config_cash" do
        ConfigCash.stub(:find) { mock_config_cash(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:config_cash).should be(mock_config_cash)
      end

      it "re-renders the 'edit' template" do
        ConfigCash.stub(:find) { mock_config_cash(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested config_cash" do
      ConfigCash.stub(:find).with("37") { mock_config_cash }
      mock_config_cash.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the config_cashes list" do
      ConfigCash.stub(:find) { mock_config_cash }
      delete :destroy, :id => "1"
      response.should redirect_to(config_cashes_url)
    end
  end

end
