require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe GexceptionAuthorizeInfosController do

  def mock_gexception_authorize_info(stubs={})
    @mock_gexception_authorize_info ||= mock_model(GexceptionAuthorizeInfo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all gexception_authorize_infos as @gexception_authorize_infos" do
      GexceptionAuthorizeInfo.stub(:all) { [mock_gexception_authorize_info] }
      get :index
      assigns(:gexception_authorize_infos).should eq([mock_gexception_authorize_info])
    end
  end

  describe "GET show" do
    it "assigns the requested gexception_authorize_info as @gexception_authorize_info" do
      GexceptionAuthorizeInfo.stub(:find).with("37") { mock_gexception_authorize_info }
      get :show, :id => "37"
      assigns(:gexception_authorize_info).should be(mock_gexception_authorize_info)
    end
  end

  describe "GET new" do
    it "assigns a new gexception_authorize_info as @gexception_authorize_info" do
      GexceptionAuthorizeInfo.stub(:new) { mock_gexception_authorize_info }
      get :new
      assigns(:gexception_authorize_info).should be(mock_gexception_authorize_info)
    end
  end

  describe "GET edit" do
    it "assigns the requested gexception_authorize_info as @gexception_authorize_info" do
      GexceptionAuthorizeInfo.stub(:find).with("37") { mock_gexception_authorize_info }
      get :edit, :id => "37"
      assigns(:gexception_authorize_info).should be(mock_gexception_authorize_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created gexception_authorize_info as @gexception_authorize_info" do
        GexceptionAuthorizeInfo.stub(:new).with({'these' => 'params'}) { mock_gexception_authorize_info(:save => true) }
        post :create, :gexception_authorize_info => {'these' => 'params'}
        assigns(:gexception_authorize_info).should be(mock_gexception_authorize_info)
      end

      it "redirects to the created gexception_authorize_info" do
        GexceptionAuthorizeInfo.stub(:new) { mock_gexception_authorize_info(:save => true) }
        post :create, :gexception_authorize_info => {}
        response.should redirect_to(gexception_authorize_info_url(mock_gexception_authorize_info))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gexception_authorize_info as @gexception_authorize_info" do
        GexceptionAuthorizeInfo.stub(:new).with({'these' => 'params'}) { mock_gexception_authorize_info(:save => false) }
        post :create, :gexception_authorize_info => {'these' => 'params'}
        assigns(:gexception_authorize_info).should be(mock_gexception_authorize_info)
      end

      it "re-renders the 'new' template" do
        GexceptionAuthorizeInfo.stub(:new) { mock_gexception_authorize_info(:save => false) }
        post :create, :gexception_authorize_info => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gexception_authorize_info" do
        GexceptionAuthorizeInfo.stub(:find).with("37") { mock_gexception_authorize_info }
        mock_gexception_authorize_info.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :gexception_authorize_info => {'these' => 'params'}
      end

      it "assigns the requested gexception_authorize_info as @gexception_authorize_info" do
        GexceptionAuthorizeInfo.stub(:find) { mock_gexception_authorize_info(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:gexception_authorize_info).should be(mock_gexception_authorize_info)
      end

      it "redirects to the gexception_authorize_info" do
        GexceptionAuthorizeInfo.stub(:find) { mock_gexception_authorize_info(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(gexception_authorize_info_url(mock_gexception_authorize_info))
      end
    end

    describe "with invalid params" do
      it "assigns the gexception_authorize_info as @gexception_authorize_info" do
        GexceptionAuthorizeInfo.stub(:find) { mock_gexception_authorize_info(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:gexception_authorize_info).should be(mock_gexception_authorize_info)
      end

      it "re-renders the 'edit' template" do
        GexceptionAuthorizeInfo.stub(:find) { mock_gexception_authorize_info(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gexception_authorize_info" do
      GexceptionAuthorizeInfo.stub(:find).with("37") { mock_gexception_authorize_info }
      mock_gexception_authorize_info.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the gexception_authorize_infos list" do
      GexceptionAuthorizeInfo.stub(:find) { mock_gexception_authorize_info }
      delete :destroy, :id => "1"
      response.should redirect_to(gexception_authorize_infos_url)
    end
  end

end
