#coding: utf-8
#coding: utf-8
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe GoodsExceptionsController do

  def mock_goods_exception(stubs={})
    @mock_goods_exception ||= mock_model(GoodsException, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all goods_exceptions as @goods_exceptions" do
      GoodsException.stub(:all) { [mock_goods_exception] }
      get :index
      assigns(:goods_exceptions).should eq([mock_goods_exception])
    end
  end

  describe "GET show" do
    it "assigns the requested goods_exception as @goods_exception" do
      GoodsException.stub(:find).with("37") { mock_goods_exception }
      get :show, :id => "37"
      assigns(:goods_exception).should be(mock_goods_exception)
    end
  end

  describe "GET new" do
    it "assigns a new goods_exception as @goods_exception" do
      GoodsException.stub(:new) { mock_goods_exception }
      get :new
      assigns(:goods_exception).should be(mock_goods_exception)
    end
  end

  describe "GET edit" do
    it "assigns the requested goods_exception as @goods_exception" do
      GoodsException.stub(:find).with("37") { mock_goods_exception }
      get :edit, :id => "37"
      assigns(:goods_exception).should be(mock_goods_exception)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created goods_exception as @goods_exception" do
        GoodsException.stub(:new).with({'these' => 'params'}) { mock_goods_exception(:save => true) }
        post :create, :goods_exception => {'these' => 'params'}
        assigns(:goods_exception).should be(mock_goods_exception)
      end

      it "redirects to the created goods_exception" do
        GoodsException.stub(:new) { mock_goods_exception(:save => true) }
        post :create, :goods_exception => {}
        response.should redirect_to(goods_exception_url(mock_goods_exception))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved goods_exception as @goods_exception" do
        GoodsException.stub(:new).with({'these' => 'params'}) { mock_goods_exception(:save => false) }
        post :create, :goods_exception => {'these' => 'params'}
        assigns(:goods_exception).should be(mock_goods_exception)
      end

      it "re-renders the 'new' template" do
        GoodsException.stub(:new) { mock_goods_exception(:save => false) }
        post :create, :goods_exception => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested goods_exception" do
        GoodsException.stub(:find).with("37") { mock_goods_exception }
        mock_goods_exception.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :goods_exception => {'these' => 'params'}
      end

      it "assigns the requested goods_exception as @goods_exception" do
        GoodsException.stub(:find) { mock_goods_exception(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:goods_exception).should be(mock_goods_exception)
      end

      it "redirects to the goods_exception" do
        GoodsException.stub(:find) { mock_goods_exception(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(goods_exception_url(mock_goods_exception))
      end
    end

    describe "with invalid params" do
      it "assigns the goods_exception as @goods_exception" do
        GoodsException.stub(:find) { mock_goods_exception(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:goods_exception).should be(mock_goods_exception)
      end

      it "re-renders the 'edit' template" do
        GoodsException.stub(:find) { mock_goods_exception(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested goods_exception" do
      GoodsException.stub(:find).with("37") { mock_goods_exception }
      mock_goods_exception.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the goods_exceptions list" do
      GoodsException.stub(:find) { mock_goods_exception }
      delete :destroy, :id => "1"
      response.should redirect_to(goods_exceptions_url)
    end
  end

end
