require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe IlConfigsController do

  def mock_il_config(stubs={})
    @mock_il_config ||= mock_model(IlConfig, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all il_configs as @il_configs" do
      IlConfig.stub(:all) { [mock_il_config] }
      get :index
      assigns(:il_configs).should eq([mock_il_config])
    end
  end

  describe "GET show" do
    it "assigns the requested il_config as @il_config" do
      IlConfig.stub(:find).with("37") { mock_il_config }
      get :show, :id => "37"
      assigns(:il_config).should be(mock_il_config)
    end
  end

  describe "GET new" do
    it "assigns a new il_config as @il_config" do
      IlConfig.stub(:new) { mock_il_config }
      get :new
      assigns(:il_config).should be(mock_il_config)
    end
  end

  describe "GET edit" do
    it "assigns the requested il_config as @il_config" do
      IlConfig.stub(:find).with("37") { mock_il_config }
      get :edit, :id => "37"
      assigns(:il_config).should be(mock_il_config)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created il_config as @il_config" do
        IlConfig.stub(:new).with({'these' => 'params'}) { mock_il_config(:save => true) }
        post :create, :il_config => {'these' => 'params'}
        assigns(:il_config).should be(mock_il_config)
      end

      it "redirects to the created il_config" do
        IlConfig.stub(:new) { mock_il_config(:save => true) }
        post :create, :il_config => {}
        response.should redirect_to(il_config_url(mock_il_config))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved il_config as @il_config" do
        IlConfig.stub(:new).with({'these' => 'params'}) { mock_il_config(:save => false) }
        post :create, :il_config => {'these' => 'params'}
        assigns(:il_config).should be(mock_il_config)
      end

      it "re-renders the 'new' template" do
        IlConfig.stub(:new) { mock_il_config(:save => false) }
        post :create, :il_config => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested il_config" do
        IlConfig.stub(:find).with("37") { mock_il_config }
        mock_il_config.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :il_config => {'these' => 'params'}
      end

      it "assigns the requested il_config as @il_config" do
        IlConfig.stub(:find) { mock_il_config(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:il_config).should be(mock_il_config)
      end

      it "redirects to the il_config" do
        IlConfig.stub(:find) { mock_il_config(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(il_config_url(mock_il_config))
      end
    end

    describe "with invalid params" do
      it "assigns the il_config as @il_config" do
        IlConfig.stub(:find) { mock_il_config(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:il_config).should be(mock_il_config)
      end

      it "re-renders the 'edit' template" do
        IlConfig.stub(:find) { mock_il_config(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested il_config" do
      IlConfig.stub(:find).with("37") { mock_il_config }
      mock_il_config.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the il_configs list" do
      IlConfig.stub(:find) { mock_il_config }
      delete :destroy, :id => "1"
      response.should redirect_to(il_configs_url)
    end
  end

end
