require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe JournalsController do

  def mock_journal(stubs={})
    @mock_journal ||= mock_model(Journal, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all journals as @journals" do
      Journal.stub(:all) { [mock_journal] }
      get :index
      assigns(:journals).should eq([mock_journal])
    end
  end

  describe "GET show" do
    it "assigns the requested journal as @journal" do
      Journal.stub(:find).with("37") { mock_journal }
      get :show, :id => "37"
      assigns(:journal).should be(mock_journal)
    end
  end

  describe "GET new" do
    it "assigns a new journal as @journal" do
      Journal.stub(:new) { mock_journal }
      get :new
      assigns(:journal).should be(mock_journal)
    end
  end

  describe "GET edit" do
    it "assigns the requested journal as @journal" do
      Journal.stub(:find).with("37") { mock_journal }
      get :edit, :id => "37"
      assigns(:journal).should be(mock_journal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created journal as @journal" do
        Journal.stub(:new).with({'these' => 'params'}) { mock_journal(:save => true) }
        post :create, :journal => {'these' => 'params'}
        assigns(:journal).should be(mock_journal)
      end

      it "redirects to the created journal" do
        Journal.stub(:new) { mock_journal(:save => true) }
        post :create, :journal => {}
        response.should redirect_to(journal_url(mock_journal))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved journal as @journal" do
        Journal.stub(:new).with({'these' => 'params'}) { mock_journal(:save => false) }
        post :create, :journal => {'these' => 'params'}
        assigns(:journal).should be(mock_journal)
      end

      it "re-renders the 'new' template" do
        Journal.stub(:new) { mock_journal(:save => false) }
        post :create, :journal => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested journal" do
        Journal.stub(:find).with("37") { mock_journal }
        mock_journal.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :journal => {'these' => 'params'}
      end

      it "assigns the requested journal as @journal" do
        Journal.stub(:find) { mock_journal(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:journal).should be(mock_journal)
      end

      it "redirects to the journal" do
        Journal.stub(:find) { mock_journal(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(journal_url(mock_journal))
      end
    end

    describe "with invalid params" do
      it "assigns the journal as @journal" do
        Journal.stub(:find) { mock_journal(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:journal).should be(mock_journal)
      end

      it "re-renders the 'edit' template" do
        Journal.stub(:find) { mock_journal(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested journal" do
      Journal.stub(:find).with("37") { mock_journal }
      mock_journal.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the journals list" do
      Journal.stub(:find) { mock_journal }
      delete :destroy, :id => "1"
      response.should redirect_to(journals_url)
    end
  end

end
