require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SendListBacksController do

  def mock_send_list_back(stubs={})
    @mock_send_list_back ||= mock_model(SendListBack, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all send_list_backs as @send_list_backs" do
      SendListBack.stub(:all) { [mock_send_list_back] }
      get :index
      assigns(:send_list_backs).should eq([mock_send_list_back])
    end
  end

  describe "GET show" do
    it "assigns the requested send_list_back as @send_list_back" do
      SendListBack.stub(:find).with("37") { mock_send_list_back }
      get :show, :id => "37"
      assigns(:send_list_back).should be(mock_send_list_back)
    end
  end

  describe "GET new" do
    it "assigns a new send_list_back as @send_list_back" do
      SendListBack.stub(:new) { mock_send_list_back }
      get :new
      assigns(:send_list_back).should be(mock_send_list_back)
    end
  end

  describe "GET edit" do
    it "assigns the requested send_list_back as @send_list_back" do
      SendListBack.stub(:find).with("37") { mock_send_list_back }
      get :edit, :id => "37"
      assigns(:send_list_back).should be(mock_send_list_back)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created send_list_back as @send_list_back" do
        SendListBack.stub(:new).with({'these' => 'params'}) { mock_send_list_back(:save => true) }
        post :create, :send_list_back => {'these' => 'params'}
        assigns(:send_list_back).should be(mock_send_list_back)
      end

      it "redirects to the created send_list_back" do
        SendListBack.stub(:new) { mock_send_list_back(:save => true) }
        post :create, :send_list_back => {}
        response.should redirect_to(send_list_back_url(mock_send_list_back))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved send_list_back as @send_list_back" do
        SendListBack.stub(:new).with({'these' => 'params'}) { mock_send_list_back(:save => false) }
        post :create, :send_list_back => {'these' => 'params'}
        assigns(:send_list_back).should be(mock_send_list_back)
      end

      it "re-renders the 'new' template" do
        SendListBack.stub(:new) { mock_send_list_back(:save => false) }
        post :create, :send_list_back => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested send_list_back" do
        SendListBack.stub(:find).with("37") { mock_send_list_back }
        mock_send_list_back.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :send_list_back => {'these' => 'params'}
      end

      it "assigns the requested send_list_back as @send_list_back" do
        SendListBack.stub(:find) { mock_send_list_back(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:send_list_back).should be(mock_send_list_back)
      end

      it "redirects to the send_list_back" do
        SendListBack.stub(:find) { mock_send_list_back(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(send_list_back_url(mock_send_list_back))
      end
    end

    describe "with invalid params" do
      it "assigns the send_list_back as @send_list_back" do
        SendListBack.stub(:find) { mock_send_list_back(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:send_list_back).should be(mock_send_list_back)
      end

      it "re-renders the 'edit' template" do
        SendListBack.stub(:find) { mock_send_list_back(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested send_list_back" do
      SendListBack.stub(:find).with("37") { mock_send_list_back }
      mock_send_list_back.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the send_list_backs list" do
      SendListBack.stub(:find) { mock_send_list_back }
      delete :destroy, :id => "1"
      response.should redirect_to(send_list_backs_url)
    end
  end

end
