require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SendListsController do

  def mock_send_list(stubs={})
    @mock_send_list ||= mock_model(SendList, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all send_lists as @send_lists" do
      SendList.stub(:all) { [mock_send_list] }
      get :index
      assigns(:send_lists).should eq([mock_send_list])
    end
  end

  describe "GET show" do
    it "assigns the requested send_list as @send_list" do
      SendList.stub(:find).with("37") { mock_send_list }
      get :show, :id => "37"
      assigns(:send_list).should be(mock_send_list)
    end
  end

  describe "GET new" do
    it "assigns a new send_list as @send_list" do
      SendList.stub(:new) { mock_send_list }
      get :new
      assigns(:send_list).should be(mock_send_list)
    end
  end

  describe "GET edit" do
    it "assigns the requested send_list as @send_list" do
      SendList.stub(:find).with("37") { mock_send_list }
      get :edit, :id => "37"
      assigns(:send_list).should be(mock_send_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created send_list as @send_list" do
        SendList.stub(:new).with({'these' => 'params'}) { mock_send_list(:save => true) }
        post :create, :send_list => {'these' => 'params'}
        assigns(:send_list).should be(mock_send_list)
      end

      it "redirects to the created send_list" do
        SendList.stub(:new) { mock_send_list(:save => true) }
        post :create, :send_list => {}
        response.should redirect_to(send_list_url(mock_send_list))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved send_list as @send_list" do
        SendList.stub(:new).with({'these' => 'params'}) { mock_send_list(:save => false) }
        post :create, :send_list => {'these' => 'params'}
        assigns(:send_list).should be(mock_send_list)
      end

      it "re-renders the 'new' template" do
        SendList.stub(:new) { mock_send_list(:save => false) }
        post :create, :send_list => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested send_list" do
        SendList.stub(:find).with("37") { mock_send_list }
        mock_send_list.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :send_list => {'these' => 'params'}
      end

      it "assigns the requested send_list as @send_list" do
        SendList.stub(:find) { mock_send_list(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:send_list).should be(mock_send_list)
      end

      it "redirects to the send_list" do
        SendList.stub(:find) { mock_send_list(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(send_list_url(mock_send_list))
      end
    end

    describe "with invalid params" do
      it "assigns the send_list as @send_list" do
        SendList.stub(:find) { mock_send_list(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:send_list).should be(mock_send_list)
      end

      it "re-renders the 'edit' template" do
        SendList.stub(:find) { mock_send_list(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested send_list" do
      SendList.stub(:find).with("37") { mock_send_list }
      mock_send_list.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the send_lists list" do
      SendList.stub(:find) { mock_send_list }
      delete :destroy, :id => "1"
      response.should redirect_to(send_lists_url)
    end
  end

end
