require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ShortFeeInfosController do

  def mock_short_fee_info(stubs={})
    @mock_short_fee_info ||= mock_model(ShortFeeInfo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all short_fee_infos as @short_fee_infos" do
      ShortFeeInfo.stub(:all) { [mock_short_fee_info] }
      get :index
      assigns(:short_fee_infos).should eq([mock_short_fee_info])
    end
  end

  describe "GET show" do
    it "assigns the requested short_fee_info as @short_fee_info" do
      ShortFeeInfo.stub(:find).with("37") { mock_short_fee_info }
      get :show, :id => "37"
      assigns(:short_fee_info).should be(mock_short_fee_info)
    end
  end

  describe "GET new" do
    it "assigns a new short_fee_info as @short_fee_info" do
      ShortFeeInfo.stub(:new) { mock_short_fee_info }
      get :new
      assigns(:short_fee_info).should be(mock_short_fee_info)
    end
  end

  describe "GET edit" do
    it "assigns the requested short_fee_info as @short_fee_info" do
      ShortFeeInfo.stub(:find).with("37") { mock_short_fee_info }
      get :edit, :id => "37"
      assigns(:short_fee_info).should be(mock_short_fee_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created short_fee_info as @short_fee_info" do
        ShortFeeInfo.stub(:new).with({'these' => 'params'}) { mock_short_fee_info(:save => true) }
        post :create, :short_fee_info => {'these' => 'params'}
        assigns(:short_fee_info).should be(mock_short_fee_info)
      end

      it "redirects to the created short_fee_info" do
        ShortFeeInfo.stub(:new) { mock_short_fee_info(:save => true) }
        post :create, :short_fee_info => {}
        response.should redirect_to(short_fee_info_url(mock_short_fee_info))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved short_fee_info as @short_fee_info" do
        ShortFeeInfo.stub(:new).with({'these' => 'params'}) { mock_short_fee_info(:save => false) }
        post :create, :short_fee_info => {'these' => 'params'}
        assigns(:short_fee_info).should be(mock_short_fee_info)
      end

      it "re-renders the 'new' template" do
        ShortFeeInfo.stub(:new) { mock_short_fee_info(:save => false) }
        post :create, :short_fee_info => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested short_fee_info" do
        ShortFeeInfo.stub(:find).with("37") { mock_short_fee_info }
        mock_short_fee_info.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :short_fee_info => {'these' => 'params'}
      end

      it "assigns the requested short_fee_info as @short_fee_info" do
        ShortFeeInfo.stub(:find) { mock_short_fee_info(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:short_fee_info).should be(mock_short_fee_info)
      end

      it "redirects to the short_fee_info" do
        ShortFeeInfo.stub(:find) { mock_short_fee_info(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(short_fee_info_url(mock_short_fee_info))
      end
    end

    describe "with invalid params" do
      it "assigns the short_fee_info as @short_fee_info" do
        ShortFeeInfo.stub(:find) { mock_short_fee_info(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:short_fee_info).should be(mock_short_fee_info)
      end

      it "re-renders the 'edit' template" do
        ShortFeeInfo.stub(:find) { mock_short_fee_info(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested short_fee_info" do
      ShortFeeInfo.stub(:find).with("37") { mock_short_fee_info }
      mock_short_fee_info.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the short_fee_infos list" do
      ShortFeeInfo.stub(:find) { mock_short_fee_info }
      delete :destroy, :id => "1"
      response.should redirect_to(short_fee_infos_url)
    end
  end

end
